### PR TITLE
Add pt-pt translations

### PR DESCRIPTION
**Pull request by joaoventura**
Portuguese translations..

Woops, I only wanted to add the Pt translations, although the commit to fix the compiling errors in ICS came along with it.
Regarding the compilation errors in ICS, it is because in the TextView of the frequency, there is no android:fontFamily in ICS (lines 28/29 of main.xml), and the Notification.Builder.build() does not exist in ICS, although is just a new name for Notification.Builder.getNotification() which exists in ICS+ but deprecated in JB.
Any chance to maintain backward compatibility with ICS?

### CODE REVIEW

**Comment by grigorig** [comment]
Thanks for the translation. The notification changes are fine I guess, but I'd really like to keep the sans-serif-light font on JB. I think I can apply the font in code instead of layout xml. I'll take a closer look tomorrow.

**Comment by grigorig** [comment]
Oh, and by the way, do you like the app, and does it work fine for you?

**Comment by ghost** [comment]
@grigorig,

I want to just say: "Wooooww". The interface has great design.

The app works on p500 if you enable it by FMRadio:
https://github.com/GenetICS/packages_apps_FMRadio/commit/7bce4a5b77d4994c645c817d3a092ec8305e9937

The problem is in MediaPlayer IOException (not defined STE_FM)... Actually this flag is for Sony devices.
It works if you change it to Exception from IOException:

https://github.com/GenetICS/packages_apps_FMRadio/commit/7bce4a5b77d4994c645c817d3a092ec8305e9937#L1L330

And I also found a bug: Default policy manager doesn't allow force using of speaker for media, so this line doesn't work:
AudioSystem.setForceUse(AudioSystem.FOR_MEDIA, AudioSystem.FORCE_SPEAKER);

I fixed it yesterday:
https://github.com/GenetICS/device_lge_p500/commit/0464cb259a5abbe59086edf29dc7be0c4ad5ef16

**Comment by joaoventura** [comment]
@grigorig, the application is working excelent, and the interface is minimalist and very intuitive. 
I think you should try to submit it to the cyanogenmod project!
The only thing I see missing is a way to enter specific frequencies manually, for when the hardware does not find the station automatically..

**Comment by grigorig** [comment]
@joaoventura, if you longclick the seek buttons, the radio will step one channel. It's not really obvious that this function exists, but most media players have it.

Unfortunately it doesn't repeat if you keep the button pressed, but I'm going to try to improve that now.

Oh, by the way, I have cherry-picked the translation and added an improved variant of the ICS compatibility patch. I'll close this here.

**Pull request closed without merging**
