### PR TITLE
Effem: Add wiredheadset / loudspeaker option for output

### PR DESCRIPTION
**Pull request by ghost**
Change-Id: Ifeed783f5c216dbfd85b3e3ab6cfcd9a99001d90

### CODE REVIEW

**Comment by ghost** [comment]
seek_supported: You guess the right thing, so you have to set freq manually.

require_bt: Broadcom chips require BT turn on to control fm chip by hcitool, otherwise fm doesn't work. P500 uses BCM4325 chip. This page contains some BT changes: https://github.com/CyanogenMod/android_packages_apps_FM/commits/gingerbread/src/com/android/fm/radio

You are right: output variable should be defined as enum, Speaker/Headset works on p500.

setForceUse: This is for just routing to speker/headset, i don't have any idea where is the correct place for it.

**Comment by grigorig** [comment]
> seek_supported: You guess the right thing, so you have to set freq manually.

The point is, which FM chips require that? I don't know any.

> setForceUse: This is for just routing to speker/headset, i don't have any idea where is the correct place for it.

If the MediaPlayer is used for (digital) FM audio, this could be used for routing to speaker also. So it should be moved above the try...catch block, so that it is always executed, no matter which type of FM audio is used.

If you update the pull request with above points fixed, I'll merge it - if you prefer I can just commit a version with those fixed myself.

**Comment by ghost** [comment]
I just copied config.xml from Fm app, I don't know which fm chip requires that either.

I love your commits and they are giving me exciting emotions and your coding style is perfect, flawless, impeccable, excellent, precise, faultless.... So, I prefer 1 commit more from you :+1: 

Which IDE do you use?

**Comment by grigorig** [comment]
> I love your commits and they are giving me exciting emotions and your coding style is perfect, flawless, impeccable, excellent, precise, faultless.... So, I prefer 1 commit more from you

LOL, I hope you aren't serious. ;)
I normally don't use any IDE, just a text editor.

Alright, I'll amend the commit myself.

**Comment by grigorig** [comment]
Committed with various changes.

**Comment by ghost** [comment]
Thank you @grigorig ...

Do you have any plan for BT changes (require_bt)?
https://github.com/CyanogenMod/android_packages_apps_FM/commits/gingerbread/src/com/android/fm/radio

I can set-up settings menus for BT if you want...
- Bluetooth behaviour on radio-off (don't change, turn-off, prompt user, restore initial state)
- Invoke Bluetooth behaviour when headset is removed

**Pull request closed without merging**
